import { Download, Plus, Trash2 } from "lucide-react";
import PageHeader from "../../components/layout/PageHeader";
import ResizableLayout from "../../components/layout/ResizableLayout";
import { useLocalDraft } from "../../hooks/useLocalDraft";
type Graph={name:string;dist:string;post:string;red:string;thal:string;area:string;noMine:string;bulk:string;pct:string};
const seed:Graph={name:"PO_JL_NR_ST_28",dist:"0,25,50",post:"227.76,227.75,227.65",red:"224.30",thal:"223.40",area:"1.60",noMine:"0",bulk:"1.52",pct:"60"};
export default function CrossSectionGraphsPage(){const [graphs,setGraphs]=useLocalDraft<Graph[]>("cross-sections-exact",[seed]);const update=(i:number,k:keyof Graph,v:string)=>setGraphs(c=>c.map((x,j)=>j===i?{...x,[k]:v}:x));return <><PageHeader title="Cross Section Graph Generator" description="Input elevation & distance data to generate sandbar cross-section graphs with auto-calculated volumes" action={<div className="flex gap-2"><button className="module-btn"><Download size={17}/>Download All Graphs PDF</button><button className="module-btn-primary" onClick={()=>setGraphs(c=>[...c,{...seed,name:`SECTION_${c.length+1}`}])}><Plus size={17}/>Add Section</button></div>}/><div className="space-y-6">{graphs.map((g,i)=><GraphCard key={i} graph={g} onChange={(k,v)=>update(i,k,v)} onDelete={()=>setGraphs(c=>c.filter((_,j)=>j!==i))}/>)}</div></>}
function GraphCard({graph:g,onChange,onDelete}:{graph:Graph;onChange:(k:keyof Graph,v:string)=>void;onDelete:()=>void}){const distances=g.dist.split(",").map(Number);const elevations=g.post.split(",").map(Number);const points=distances.map((d,i)=>({x:d,y:elevations[i]??0})).filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));const minX=Math.min(...points.map(p=>p.x),0),maxX=Math.max(...points.map(p=>p.x),1),minY=Math.min(...points.map(p=>p.y),Number(g.thal)||0),maxY=Math.max(...points.map(p=>p.y),Number(g.red)||1);const coords=points.map(p=>`${40+((p.x-minX)/(maxX-minX||1))*520},${250-((p.y-minY)/(maxY-minY||1))*190}`).join(" ");const thickness=Math.max(0,Number(g.red)-Number(g.thal));const volume=Number(g.area)*10000*thickness;const mineral=volume*Number(g.bulk)*(Number(g.pct)/100);
  const leftPanel = <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1 p-2">{([['dist','Distance values (comma separated)'],['post','Post-monsoon elevations'],['red','Reduced Level'],['thal','Thalweg Level'],['area','Area (Ha)'],['noMine','No Mining Zone (m)'],['bulk','Bulk Density'],['pct','Recoverable Mineral (%)']] as [keyof Graph,string][]).map(([k,l])=><label key={k} className="text-sm font-semibold">{l}<input value={g[k]} onChange={e=>onChange(k,e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal outline-none focus:border-blue-500"/></label>)}</div>;
  const rightPanel = <div className="p-2"><div className="rounded-xl bg-slate-900 p-4 text-white"><div className="grid grid-cols-3 gap-3 text-center"><Metric label="Thickness" value={`${thickness.toFixed(2)} m`}/><Metric label="Volume" value={`${volume.toFixed(0)} m³`}/><Metric label="Mineral" value={`${mineral.toFixed(0)} MT`}/></div></div><div className="mt-4 rounded-xl border bg-slate-50 p-3"><p className="mb-2 text-xs font-bold uppercase text-slate-500">Live cross-section preview</p><svg viewBox="0 0 600 280" className="w-full bg-white"><line x1="40" y1="250" x2="570" y2="250" stroke="#94a3b8"/><line x1="40" y1="30" x2="40" y2="250" stroke="#94a3b8"/><polyline points={coords} fill="none" stroke="#2563eb" strokeWidth="4"/><line x1="40" y1={250-((Number(g.red)-minY)/(maxY-minY||1))*190} x2="570" y2={250-((Number(g.red)-minY)/(maxY-minY||1))*190} stroke="#f59e0b" strokeDasharray="8 5"/><text x="45" y="24" fontSize="12" fill="#475569">Elevation (m)</text><text x="490" y="270" fontSize="12" fill="#475569">Distance (m)</text></svg></div></div>;
  return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><input value={g.name} onChange={e=>onChange("name",e.target.value)} className="rounded-lg border px-3 py-2 font-bold"/><button onClick={onDelete} className="rounded p-2 text-red-500 hover:bg-red-50"><Trash2 size={18}/></button></div><div className="p-3"><ResizableLayout leftPanel={leftPanel} rightPanel={rightPanel} leftPanelDefaultSize={40} rightPanelDefaultSize={60} /></div></section>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="text-xs text-slate-300">{label}</p><p className="mt-1 font-bold">{value}</p></div>}
