import { ArrowDown, ArrowUp, Image, Plus, Trash2, Upload } from "lucide-react";
import PageHeader from "../../components/layout/PageHeader";
import ResizableLayout from "../../components/layout/ResizableLayout";
import { useLocalDraft } from "../../hooks/useLocalDraft";
type Plate={name:string;summary:string;fileName?:string};
const initial:Plate[]=[{name:"Plate 1 - Pre/Post Monsoon Cross Section",summary:"Auto-generated elevation chart for sand volume calculation."},{name:"Plate 2 - Geological Subsurface Map",summary:"Detailed lithological boundaries and soil types."}];
export default function PlatesPage(){const [plates,setPlates]=useLocalDraft<Plate[]>("plates-exact",initial);const update=(i:number,p:Partial<Plate>)=>setPlates(c=>c.map((x,j)=>j===i?{...x,...p}:x));const move=(i:number,d:number)=>setPlates(c=>{const n=[...c];[n[i],n[i+d]]=[n[i+d],n[i]];return n});
  const leftPanel = <div className="space-y-4">{plates.map((plate,i)=><article key={i} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-xl bg-purple-50 text-purple-600"><Image size={22}/></span><div className="min-w-0 flex-1"><input value={plate.name} onChange={e=>update(i,{name:e.target.value})} className="w-full rounded-lg border px-3 py-2 font-bold outline-none focus:border-blue-500"/><textarea value={plate.summary} onChange={e=>update(i,{summary:e.target.value})} rows={2} className="mt-2 w-full rounded-lg border px-3 py-2 text-sm outline-none focus:border-blue-500"/><label className="module-btn mt-2 cursor-pointer"><Upload size={16}/>{plate.fileName||"Upload PDF / Image"}<input type="file" accept="application/pdf,image/*" hidden onChange={e=>e.target.files?.[0]&&update(i,{fileName:e.target.files[0].name})}/></label></div><div><button disabled={i===0} onClick={()=>move(i,-1)} className="block rounded p-2 disabled:opacity-30"><ArrowUp size={17}/></button><button disabled={i===plates.length-1} onClick={()=>move(i,1)} className="block rounded p-2 disabled:opacity-30"><ArrowDown size={17}/></button><button onClick={()=>setPlates(c=>c.filter((_,j)=>j!==i))} className="block rounded p-2 text-red-500"><Trash2 size={17}/></button></div></div></article>)}</div>;
  const rightPanel = <aside className="h-full rounded-2xl border bg-slate-100 p-4"><p className="mb-3 text-xs font-bold uppercase text-slate-500">Live plate index preview</p><div className="min-h-[560px] bg-white p-8 shadow"><p className="text-center text-xs font-bold uppercase tracking-widest">District Survey Report</p><h2 className="mt-3 text-center text-xl font-bold uppercase">List of Plates</h2><div className="mt-8 space-y-5">{plates.map((p,i)=><div key={i} className="border-b pb-3"><p className="font-bold">{p.name}</p><p className="text-sm text-slate-600">{p.summary}</p>{p.fileName&&<p className="mt-1 text-xs text-blue-600">Attached: {p.fileName}</p>}</div>)}</div></div></aside>;
  return <><PageHeader title="Plate Section" description="Upload PDFs and images. Each entry becomes a plate in the final DSR report." action={<button className="module-btn-primary" onClick={()=>setPlates(c=>[...c,{name:`Plate ${c.length+1} - Enter Title`,summary:"Enter plate description"}])}><Plus size={17}/>Add Plate</button>}/><div className="h-[calc(100vh-12rem)] flex"><ResizableLayout leftPanel={leftPanel} rightPanel={rightPanel} leftPanelDefaultSize={60} rightPanelDefaultSize={40} /></div></>}
